# This file was generated by GoReleaser. DO NOT EDIT.
cask "lettermint" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "2d9d8c35d38783562f08f072d7d6c8198738bf56e3c17436a161979643f7f555"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff090744377edde5cc5a7ba79303cdbf253ec085031ddcffce2a1c4283974110"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "lettermint"
  desc "Send email and test Lettermint webhooks locally"
  homepage "https://lettermint.co/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lettermint"

  # No zap stanza required
end
