# This file was generated by GoReleaser. DO NOT EDIT.
cask "lettermint" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "64da482c090653736900a6a96aacb1e6fe5b73459883ad968723b7f614cffa78"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e69b677a6777acb268f2370296198828d9f2adb29340d7fb9d2b8efc0b4689f"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "lettermint"
  desc "Send email and test Lettermint webhooks locally"
  homepage "https://lettermint.co/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lettermint"

  # No zap stanza required
end
