# This file was generated by GoReleaser. DO NOT EDIT.
cask "lettermint" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "1e31b24cb2b738508837016db031827e4fcac6d1dfd10707ccbe1d697e92b688"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "69d35b9457b74ce4ad9c16a20579025bff7ee74625d36ccdfc6aefa3bd162ece"
      url "https://github.com/lettermint/lettermint-cli/releases/download/v#{version}/lettermint_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "lettermint"
  desc "Send email and test Lettermint webhooks locally"
  homepage "https://lettermint.co/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lettermint"

  # No zap stanza required
end
